package com.ringly.ringly.config;

import android.support.annotation.DrawableRes;
import android.support.annotation.StringRes;

import com.google.common.collect.ImmutableSet;
import com.ringly.ringly.R;

import java.util.Set;

@SuppressWarnings({"HardCodedStringLiteral", "InstanceVariableNamingConvention", "PublicField"})
public enum NotificationType {
    // DO NOT CHANGE these names, they are persisted in the user preferences

    // initially enabled:
    PHONE_CALL(R.drawable.notifications_phone_call, R.string.phone_call,
            Color.BLUE, Vibration.FOUR),
    TEXT_MESSAGE(R.drawable.notifications_text_message, R.string.text_message,
            Color.GREEN, Vibration.THREE, "com.android.mms"), //TODO Added this package because SMS with WifiCalling doesnt generate
                                                              //ThelephonyReceiver event, but its pending to add the logic to get the phone number
    CALENDAR(R.drawable.notifications_calendar, R.string.calendar,
            Color.RED, Vibration.ONE,
            "com.android.calendar", "com.google.android.calendar"),

    // initially disabled:
    ACCUWEATHER(R.drawable.notifications_accuweather, R.string.accuweather, "com.accuweather.android"),
    AIRBNB(R.drawable.notifications_airbnb, R.string.airbnb, "com.airbnb.android"),
    ALLO(R.drawable.notifications_allo, R.string.allo, "com.google.android.apps.fireball"),
    AMAZON_ALEXA(R.drawable.notifications_amazon_alexa, R.string.amazon_alexa, "com.amazon.dee.app"),
    AMERICAN_AIRLINES(R.drawable.notifications_american_airlines, R.string.american_airlines, "com.aa.android"),
    ANDROID_EMAIL(R.drawable.notifications_email, R.string.android_email,
            "com.android.email", "com.google.android.email"),
    ANYDO(R.drawable.notifications_anydo, R.string.anydo, "com.anydo"),
    AP(R.drawable.notifications_ap, R.string.ap, "mnn.Android"),
    ARLO(R.drawable.notifications_arlo, R.string.arlo, "com.netgear.android"),
    ASANA(R.drawable.notifications_asana, R.string.asana, "com.asana.app"),
    AVOCADO(R.drawable.notifications_avocado, R.string.avocado, "io.avocado.android"),
    BASECAMP3(R.drawable.notifications_basecamp3, R.string.basecamp3, "com.basecamp.bc3"),
    BBM(R.drawable.notifications_bbm, R.string.bbm, "com.bbm"),
    BETWEEN(R.drawable.notifications_between, R.string.between, "kr.co.vcnc.android.couple"),
    BIRCHBOX(R.drawable.notifications_birchbox, R.string.birchbox, "com.birchbox.birchbox"),
    BUFFER(R.drawable.notifications_buffer, R.string.buffer, "org.buffer.android"),
    BUMBLE(R.drawable.notifications_bumble, R.string.bumble, "com.bumble.app"),
    BSAFE(R.drawable.notifications_bsafe, R.string.bsafe, "com.bipper.app.bsafe"),
    CHOMP(R.drawable.notifications_chomp, R.string.chomp, "com.p1.chompsms"),
    CLASSDOJO(R.drawable.notifications_classdojo, R.string.classdojo, "com.classdojo.android"),
    CLEVERLOOP(R.drawable.notifications_cleverloop, R.string.cleverloop, "com.cleverloop.android"),
    CLUE(R.drawable.notifications_clue, R.string.clue, "com.clue.android"),
    COACHELLA(R.drawable.notifications_coachella, R.string.coachella, "com.goldenvoice.coachellafest"),
    COUPLE(R.drawable.notifications_couple, R.string.couple, "com.tenthbit.juliet"),
    COVET_FASHION(R.drawable.notifications_covet, R.string.covet, "com.crowdstar.covetfashion"),
    COZI(R.drawable.notifications_cozi, R.string.cozi, "com.cozi.androidfree"),
    DEXCOM_FOLLOW(R.drawable.notifications_dexcom_follow, R.string.dexcom_follow, "com.dexcom.follow"),
    DOC_HALO(R.drawable.notifications_doc_halo, R.string.doc_halo, "com.dochalo.dochalo"),
    DOCUSIGN(R.drawable.notifications_docusign, R.string.docusign, "com.docusign.ink"),
    DROPCAM(R.drawable.notifications_dropcam, R.string.dropcam, "com.dropcam.android"),
    EBAY(R.drawable.notifications_ebay, R.string.ebay, "com.ebay.mobile"),
    EMAIL(R.drawable.notifications_email, R.string.email, "notification removed" ),//This was removed, this was replaced with ANDROID_EMAIL, GMAIL, INBOX
    ENDOMONDO(R.drawable.notifications_endomondo, R.string.endomondo, "com.endomondo.android"),
    ESPN(R.drawable.notifications_espn, R.string.espn, "com.espn.score_center"),
    ETSY(R.drawable.notifications_etsy, R.string.etsy, "com.etsy.android"),
    EVERNOTE(R.drawable.notifications_evernote, R.string.evernote, "com.evernote"),
    FACEBOOK(R.drawable.notifications_facebook, R.string.facebook, "com.facebook.katana"),
    FACEBOOK_MESSENGER(R.drawable.notifications_facebook_messenger, R.string.facebook_messenger, "com.facebook.orca"),
    FACEBOOK_PAGES_MANAGER(R.drawable.notifications_fb_pma, R.string.facebook_pma, "com.facebook.pages.app"),
//    FIND_MY_FRIENDS(R.drawable.notifications_find_my_friends, R.string.find_my_friends, "com.fsp.android.friendlocator"), TODO CHECK
    FITBIT(R.drawable.notifications_fitbit, R.string.fitbit, "com.fitbit.FitbitMobile"),
    FLY_DELTA(R.drawable.notifications_fly_delta, R.string.fly_delta, "com.delta.mobile.android"),
    FLYWHEEL(R.drawable.notifications_flywheel, R.string.flywheel, "com.upstartmobile.Cabulous"),
    FOX_NEWS(R.drawable.notifications_fox_news, R.string.fox_news, "com.foxnews.android"),
    GILT(R.drawable.notifications_gilt, R.string.gilt, "com.gilt.android"),
    GLIDE(R.drawable.notifications_glide, R.string.glide, "com.glidetalk.glideapp"),
    GLIP(R.drawable.notifications_glip, R.string.glip, "com.glip.mobile"),
    GLOOKO(R.drawable.notifications_glooko, R.string.glooko, "com.glooko.logbook"),
    GLOW(R.drawable.notifications_glow, R.string.glow, "com.glow.android"),
    GMAIL(R.drawable.notifications_gmail, R.string.gmail, "com.google.android.gm"),
    GOOD(R.drawable.notifications_good, R.string.good, "com.good.android.gfe"),
    GOODREADS(R.drawable.notifications_goodreads, R.string.goodreads, "com.goodreads"),
    GOOGLE_DUO(R.drawable.notifications_google_duo, R.string.google_duo, "com.google.android.apps.tachyon"),
    GOOGLE_EXPRESS(R.drawable.notifications_google_express, R.string.google_express, "com.google.android.apps.shopping.express"),
    GOOGLE_FIT(R.drawable.notifications_google_fit, R.string.google_fit, "com.google.android.apps.fitness"),
    GOOGLE_KEEP(R.drawable.notifications_google_keep, R.string.google_keep, "com.google.android.keep"),
    GOOGLE_MAPS(R.drawable.notifications_google_maps, R.string.google_maps, "com.google.android.apps.maps"),
    GOOGLE_NOW(R.drawable.notifications_google_now, R.string.google_now, "com.google.android.googlequicksearchbox"),
    GOOGLE_VOICE(R.drawable.notifications_google_voice, R.string.google_voice, "com.google.android.apps.googlevoice"),
    GROUPME(R.drawable.notifications_groupme, R.string.groupme, "com.groupme.android"),
    GRUBHUB(R.drawable.notifications_grubhub, R.string.grubhub, "com.grubhub.android"),
    HANGOUTS(R.drawable.notifications_hangouts, R.string.hangouts, "com.google.android.talk"),
    HAPPN(R.drawable.notifications_happn, R.string.happn, "com.ftw_and_co.happn"),
    HEADSPACE(R.drawable.notifications_headspace, R.string.headspace, "com.getsomeheadspace.android"),
    HIDRATE(R.drawable.notifications_hidrate, R.string.hidrate, "hidratenow.com.hidrate.hidrateandroid"),
    HINGE(R.drawable.notifications_hinge, R.string.hinge, "co.hinge.mobile.android"),
    HIPCHAT(R.drawable.notifications_hipchat, R.string.hipchat, "com.hipchat"),
    HOMEBOY(R.drawable.notifications_homeboy, R.string.homeboy, "com.homeboy"),
    HOOTSUITE(R.drawable.notifications_hootsuite, R.string.hootsuite, "com.hootsuite.droid.full"),
    HOOKS(R.drawable.notifications_hooks, R.string.hooks, "com.hooks.android"),
    IFTTT(R.drawable.notifications_ifttt, R.string.ifttt, "com.ifttt.ifttt"),
    INBOX(R.drawable.notifications_inbox, R.string.inbox, "com.google.android.apps.inbox"),
    INSTACART(R.drawable.notifications_instacart, R.string.instacart, "com.instacart.client"),
    INSTAGRAM(R.drawable.notifications_instagram, R.string.instagram, "com.instagram.android"),
    JETBLUE(R.drawable.notifications_jetblue, R.string.jetblue, "com.jetblue.JetBlueAndroid"),
    KAKAOTALK(R.drawable.notifications_kakaotalk, R.string.kakaotalk, "com.kakao.talk"),
    KIK(R.drawable.notifications_kik, R.string.kik, "kik.android"),
    LATIMES(R.drawable.notifications_la_times, R.string.la_times, "com.apptivateme.next.la"),
    LETGO(R.drawable.notifications_letgo, R.string.letgo, "com.abtnprojects.ambatana"),
    LIFE360(R.drawable.notifications_life360, R.string.life360, "com.life360.android.safetymapd"),
    LINE(R.drawable.notifications_line, R.string.line, "jp.naver.line.android"),
    LINKEDIN(R.drawable.notifications_linkedin, R.string.linkedin, "com.linkedin.android"),
    LOSEIT(R.drawable.notifications_lose_it, R.string.lose_it, "com.fitnow.loseit"),
    LYFT(R.drawable.notifications_lyft, R.string.lyft, "me.lyft.android"),
    MAPLE(R.drawable.notifications_maple, R.string.maple, "com.maple.Maple"),
    MAPMYDOGWALK(R.drawable.notifications_mapmydogwalk, R.string.mapmydogwalk, "com.mapmydogwalk.android2"),
    MAPMYFITNESS(R.drawable.notifications_mapmyfitness, R.string.mapmyfitness, "com.mapmyfitness.android2"),
    MAPMYHIKE(R.drawable.notifications_mapmyhike, R.string.mapmyhike, "com.mapmyhike.android2"),
    MAPMYRIDE(R.drawable.notifications_mapmyride, R.string.mapmyride, "com.mapmyride.android2"),
    MAPMYRUN(R.drawable.notifications_mapmyrun, R.string.mapmyrun, "com.mapmyrun.android2"),
    MAPMYWALK(R.drawable.notifications_mapmywalk, R.string.mapmywalk, "com.mapmywalk.android2"),
    MEDISAFE(R.drawable.notifications_medisafe, R.string.medisafe, "com.medisafe.android.client"),
    MERCARI(R.drawable.notifications_mercari, R.string.mercari, "com.mercariapp.mercari"),
    MICROSOFT_OUTLOOK(R.drawable.notifications_microsoft_outlook, R.string.microsoft_outlook, "com.microsoft.office.outlook"),
    MINT(R.drawable.notifications_mint, R.string.mint, "com.mint"),
    MOBILEIRON(R.drawable.notifications_mobileiron, R.string.mobileiron, "com.mobileiron"),
    MYBRIGHTDAY(R.drawable.notifications_mybrightday, R.string.my_bright_day, "com.brighthorizons.mybrightday"),
    MYFITNESSPAL(R.drawable.notifications_myfitnesspal, R.string.myfitnesspal, "com.myfitnesspal.android"),
    MYIDEALDOCTOR(R.drawable.notifications_myidealdoctor, R.string.myidealdoctor, "com.myidealdoctor.patient"),
    MYPILL(R.drawable.notifications_mypill, R.string.mypill, "com.bouqt.mypill"),
    MYPILLBOX(R.drawable.notifications_mypillbox, R.string.mypillbox, "com.tobeamaster.mypillbox"),
    MYZONE(R.drawable.notifications_myzone, R.string.myzone, "com.myzone.myzoneble"),
    NBC_SPORTS(R.drawable.notifications_nbc_sports, R.string.nbc_sports, "air.com.nbcuni.com.nbcsports.liveextra"),
    NEST(R.drawable.notifications_nest, R.string.nest, "com.nest.android"),
    NET_A_PORTER(R.drawable.notifications_net_a_porter, R.string.net_a_porter, "com.nap"),
    NINE(R.drawable.notifications_nine, R.string.nine, "com.ninefolders.hd3"),
    NTOUCH(R.drawable.notifications_ntouch, R.string.ntouch, "com.sorenson.mvrs.android"),
    NYTIMES(R.drawable.notifications_nytimes, R.string.nytimes, "com.nytimes.android"),
    OFFERUP(R.drawable.notifications_offerup, R.string.offerup, "com.offerup"),
    OKCUPID(R.drawable.notifications_okcupid, R.string.okcupid, "com.okcupid.okcupid"),
    OPSGENIE(R.drawable.notifications_opsgenie, R.string.opsgenie, "com.ifountain.opsgenie"),
    PACIFICA(R.drawable.notifications_pacifica, R.string.pacifica, "com.pacificalabs.pacifica"),
    PAGERDUTY(R.drawable.notifications_pagerduty, R.string.pagerduty, "com.pagerduty.android"),
    PARK_CC(R.drawable.notifications_park_cc, R.string.park_cc, "com.parkgenius.Park.CRP"),
    PARKMOBILE(R.drawable.notifications_parkmobile, R.string.parkmobile, "net.sharewire.parkmobilev2"),
    PAYPAL(R.drawable.notifications_paypal, R.string.paypal, "com.paypal.android.p2pmobile"),
    PERIOD_TRACKER_DELUXE(R.drawable.notifications_period_tracker_deluxe, R.string.period_tracker_deluxe, "com.period.tracker.deluxe"),
    PERISCOPE(R.drawable.notifications_periscope, R.string.periscope, "tv.periscope.android"),
    PINTEREST(R.drawable.notifications_pinterest, R.string.pinterest, "com.pinterest"),
    PLANN(R.drawable.notifications_plann, R.string.plann, "com.webhaus.planyourgramScheduler"),
    POCKETSUITE(R.drawable.notifications_pocketsuite, R.string.pocketsuite, "com.pocketsuite"),
    POSHMARK(R.drawable.notifications_poshmark, R.string.poshmark, "com.poshmark.app"),
    PUSHBULLET(R.drawable.notifications_pushbullet, R.string.pushbullet, "com.pushbullet.android"),
    RANDOMLY_REMINDME(R.drawable.notifications_randomly_remindme, R.string.randomly_remindme, "jamesmorrisstudios.com.randremind"),
    RING(R.drawable.notifications_ring, R.string.ring, "com.ringapp"),
    ROBINHOOD(R.drawable.notifications_robinhood, R.string.robinhood, "com.robinhood.android"),
    ROKET_CHAT(R.drawable.notifications_rocket_chat, R.string.rocket_chat, "com.konecty.rocket.chat"),
    ROVER(R.drawable.notifications_rover, R.string.rover, "com.rover.android"),
    SALESFORCE1(R.drawable.notifications_salesforce1, R.string.salesforce1, "com.salesforce.chatter"),
    SALESFORCE_INBOX(R.drawable.notifications_salesforce_inbox, R.string.salesforce_inbox, "com.relateiq.android"),
    SELL_ON_ETSY(R.drawable.notifications_soe, R.string.sellonetsy, "com.etsy.android.soe"),
    SHAZAM(R.drawable.notifications_shazam, R.string.shazam, "com.shazam.android"),
    SHIPT(R.drawable.notifications_shipt, R.string.shipt, "com.shipt.groceries"),
    SHOPIFY(R.drawable.notifications_shopify, R.string.shopify, "com.shopify.mobile"),
    S_HEALTH(R.drawable.notifications_s_health, R.string.s_health, "com.sec.android.app.shealth"),
    SIMPLE(R.drawable.notifications_simple, R.string.simple, "com.banksimple"),
    SKYPE(R.drawable.notifications_skype, R.string.skype, "com.skype.raider"),
    SLACK(R.drawable.notifications_slack, R.string.slack, "com.Slack"),
    SLEEP_CYCLE(R.drawable.notifications_sleep_cycle, R.string.sleep_cycle, "com.northcube.sleepcycle"),
    SNAPCHAT(R.drawable.notifications_snapchat, R.string.snapchat, "com.snapchat.android"),
    SOUNDHOUND(R.drawable.notifications_soundhound, R.string.soundhound, "com.melodis.midomiMusicIdentifier.freemium"),
    SPOK_MOBILE(R.drawable.notifications_spok_mobile, R.string.spok_mobile, "com.amcom.MEClient"),
    SPOT_ON(R.drawable.notifications_spot_on, R.string.spot_on, "com.spotontracker"),
    SPRING(R.drawable.notifications_spring, R.string.spring, "com.jellolabs.spring.android"),
    SPROUT_SOCIAL(R.drawable.notifications_sproutsocial, R.string.sproutsocial, "com.sproutsocial.android"),
    SUNRISE(R.drawable.notifications_sunrise, R.string.sunrise, "am.sunrise.android.calendar"),
    TADPOLES(R.drawable.notifications_tadpoles, R.string.tadpoles, "com.tadpoles.parent"),
    TALKSPACE(R.drawable.notifications_talkspace, R.string.talkspace, "com.talkspace.talkspaceapp"),
    TELEGRAM(R.drawable.notifications_telegram, R.string.telegram, "org.telegram.messenger"),
    TEXTME(R.drawable.notifications_textme, R.string.textme, "com.textmeinc.textme"),
    TEXTRA(R.drawable.notifications_textra, R.string.textra, "com.textra"),
    TEXTSECURE(R.drawable.notifications_signal, R.string.signal, "org.thoughtcrime.securesms"),
    THE_NEW_STAND(R.drawable.notifications_the_new_stand, R.string.the_new_stand, "com.the_new_stand.TheNewStand"),
    THESCORE(R.drawable.notifications_thescore, R.string.thescore, "com.fivemobile.thescore"),
    THUUZ(R.drawable.notifications_thuuz, R.string.thuuz, "com.thuuz.mob"),
    TIGERTEXT(R.drawable.notifications_tigertext, R.string.tigertext, "com.tigertext"),
    TINDER(R.drawable.notifications_tinder, R.string.tinder, "com.tinder"),
    TODOIST(R.drawable.notifications_todoist, R.string.todoist, "com.todoist"),
    TOUCHDOWN(R.drawable.notifications_touchdown, R.string.touchdown, "com.nitrodesk.droid20.nitroid"),
    TRELLO(R.drawable.notifications_trello, R.string.trello, "com.trello"),
    TRIPIT(R.drawable.notifications_tripit, R.string.tripit, "com.tripit"),
    TUMBLR(R.drawable.notifications_tumblr, R.string.tumblr, "com.tumblr"),
    TWITTER(R.drawable.notifications_twitter, R.string.twitter, "com.twitter.android"),
    UBER(R.drawable.notifications_uber, R.string.uber, "com.ubercab"),
    UNITED(R.drawable.notifications_united, R.string.united, "com.united.mobile.android"),
    UP_SMART_COACH(R.drawable.notifications_up_smart_coach, R.string.up_smart_coach, "com.jawbone.upopen"),
    VECTOR_SECURITY(R.drawable.notifications_vector_security, R.string.vector_security, "com.alarm.alarmmobile.android.vector"),
    VENMO(R.drawable.notifications_venmo, R.string.venmo, "com.venmo"),
    VIBER(R.drawable.notifications_viber, R.string.viber, "com.viber.voip"),
    VINE(R.drawable.notifications_vine, R.string.vine, "co.vine.android"),
    VIRGIN_PULSE(R.drawable.notifications_virgin_pulse, R.string.virgin_pulse, "com.virginpulse.virginpulse"),
    VOXER(R.drawable.notifications_voxer, R.string.voxer, "com.rebelvox.voxer"),
    WATERIN(R.drawable.notifications_waterin, R.string.waterin, "com.wearemothership.tubfish.waterin"),
    WAZE(R.drawable.notifications_waze, R.string.waze, "com.waze"),
    WECHAT(R.drawable.notifications_wechat, R.string.wechat, "com.tencent.mm"),
    WEIGHT_WATCHERS(R.drawable.notifications_weight_watchers, R.string.weight_watchers, "com.weightwatchers.mobile"),
    WHATSAPP(R.drawable.notifications_whatsapp, R.string.whatsapp, "com.whatsapp"),
    WEATHER_CHANNEL(R.drawable.notifications_weather_channel, R.string.weather_channel, "com.weather.Weather"),
    WICKR(R.drawable.notifications_wickr, R.string.wickr, "com.mywickr.wickr2"),
    WIRE(R.drawable.notifications_wire, R.string.wire, "com.wire"),
    WUNDERLIST(R.drawable.notifications_wunderlist, R.string.wunderlist, "com.wunderkinder.wunderlistandroid"),
    YAHOOMAIL(R.drawable.notifications_ymail, R.string.yahoomail, "com.yahoo.mobile.client.android.mail"),
    YAHOO_FANTASY(R.drawable.notifications_yahoo_fantasy, R.string.yahoo_fantasy, "com.yahoo.mobile.client.android.fantasyfootball"),
    ZENDESK_SUPPORT(R.drawable.notifications_zendesk_support, R.string.zendesk_support, "com.zendesk.android"),
    微博(R.drawable.notifications_weibo, R.string.weibo, "com.sina.weibo"),
    ;


    @DrawableRes public final int iconId;
    @StringRes public final int nameId;
    public final Color defaultColor;
    public final Vibration defaultVibration;
    public final Set<String> ids;

    NotificationType(@DrawableRes final int iconId, @StringRes final int nameId, final String... ids) {
        this(iconId, nameId, Color.NONE, Vibration.NONE, ids);
    }

    NotificationType(@DrawableRes final int iconId, @StringRes final int nameId,
                     final Color defaultColor, final Vibration defaultVibration,
                     final String... ids) {
        this.iconId = iconId;
        this.nameId = nameId;
        this.defaultColor = defaultColor;
        this.defaultVibration = defaultVibration;
        this.ids = ImmutableSet.copyOf(ids);
    }
}
